### ISSUE TITLE
Allow to request the question

### ISSUE THREAD

**Issue by m4rcster** [m4rcster/plantbasedchamp#1]
Currently if you recceive the question of the day, and for example ask for your score, you cannot get the question back.

Should we allow to

> You didn't ask me today
> Gimme the question
> Question

or

>I had <plant, veggi, mixed> yesterday
>I ate <plant, veggi, mixed> yesterday

**Comment by chpapadoco** [comment]
Hi, 
I would say that for the beta version you should not be able to come back. 
What do you think?
