### ISSUE TITLE
Post announcing beta testing

### ISSUE THREAD

**Issue by m4rcster** [m4rcster/plantbasedchamp#10]
@chpapadoco do you want to create a post that says something like:

[Nice image of a bot, the koala or whatever]
> we are currently beta testing our bot. if you want to try it out, leave a comment and we will add you

You might want to reforumlate

**Comment by chpapadoco** [comment]
Post performed. Consider issue closed?

**Comment by m4rcster** [comment]
Yes close the issue when done
