### ISSUE TITLE
New test users 

### ISSUE THREAD

**Issue by chpapadoco** [m4rcster/plantbasedchamp#17]
Marc Jungo 
Francois jacquet 
Marc segmüller

**Comment by m4rcster** [comment]
![image](https://cloud.githubusercontent.com/assets/14793583/23091124/26bcc7a4-f5af-11e6-8714-4209d024e925.png)

@chpapadoco  Please provide facebook username. Could not find francois

**Comment by chpapadoco** [comment]
hi Marc,
https://www.facebook.com/francois.jaquet
https://www.facebook.com/carole.charles.54

**Comment by chpapadoco** [comment]
karsten Bagger should also be added
